language: python
python:
  - "3.6.0"
services:
  - postgresql

env:
  global:
  -APP_SETTINGS=testing  
install:
  - pip install -r requirements.txt 

before_script:
  - "psql -c 'create database testdb;' -U postgres"

script: 
  - pytest --cov=.
  - coverage
  - coveralls
 
after_success:
  - coveralls  